name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - id: component
      uses: actions-rs/components-nightly@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
